### ISSUE TITLE
"The specified module could not be found"

### ISSUE THREAD

**Issue by FreshCoderM** [CengSin/oracle#1]
2020/10/07 14:48:17 initial database connect……
2020/10/07 14:48:17 ORA-00000: DPI-1047: Cannot locate a 64-bit Oracle Client library: "The specified module could not be found". See https://oracle.github.io/odpi/doc/installation.html#windows for help

I start with documentation，but error coming ，please help me ,

I have already installed oracle  and set the PATH ~

But it still can't  solve this problem

**Comment by CengSin** [comment]
you should install oracle client, download url writed readme.md and set LD_LIBRARY_PATH env
 variable = oracle client path
