### ISSUE TITLE
迁移问题

### ISSUE THREAD

**Issue by xiyichan** [CengSin/oracle#11]
请问可以自动注册表吗？我测试的时候好像是不可以的

**Comment by xiyichan** [comment]
而且type怎么指定类型

**Comment by CengSin** [comment]
oracle版本12C+应该是可以主动注册表的，而且可以指定type。

**Comment by xiyichan** [comment]
是高于12C的版本吗?或者是我指定的type有错误？
![image](https://user-images.githubusercontent.com/34647972/120262888-3482be80-c2cd-11eb-8eb0-8c4dadd62a4e.png)
还有请问是不是不能用自增主键，谢谢大佬。

**Comment by xiyichan** [comment]
然后有什么问题，我可以参与开发进去。

**Comment by CengSin** [comment]
![image](https://user-images.githubusercontent.com/23357893/120274294-386d0b80-c2e2-11eb-9822-912b1fa36b9c.png)
fixed!如果需要主键自增需要加上`autoIncrement`

**Comment by xiyichan** [comment]
![image](https://user-images.githubusercontent.com/34647972/120274558-9bf73900-c2e2-11eb-969a-85cbf6defb08.png)
怎么我就不行..这么奇怪吗

**Comment by CengSin** [comment]
你更新一下mod

**Comment by xiyichan** [comment]
好像不可以大佬已经更oracle 的mod 但是还是1.0.0

**Comment by CengSin** [comment]
可以fork本仓库，然后克隆到本地，在mod文件中replace一下使用。

```
replace github.com/cengsin/oracle => repo local path
```

**Comment by xiyichan** [comment]
这不太好，我打包是在linux

**Comment by xiyichan** [comment]
我看了大佬的代码的修改..这是要让我自己现改现用吧哈哈哈。然后现在autoIncrement还是用不了。

**Comment by CengSin** [comment]
![image](https://user-images.githubusercontent.com/23357893/120276830-c991b180-c2e5-11eb-98ed-a441725b642a.png)
`autoincrement`可用，你的oracle版本是什么

**Comment by xiyichan** [comment]
还真是别人装的版本不够高

**Comment by xiyichan** [comment]
大佬很强，如果有别的BUG我及时反馈，要上项目了。
