### ISSUE TITLE
feature:update godror package will be insert faster than this version

### ISSUE THREAD

**Issue by Max-Cheng** [CengSin/oracle#15]
在本地更新godror依赖版本后,gorm批量插入的速度更快了

**Comment by CengSin** [comment]
你可以修改godror的依赖版本，之后提交一个合并申请。

**Comment by Max-Cheng** [comment]
今天在本地测试了一下，非常奇怪，在开发环境有显著的提升，本地测试反而区别不大，这个feature需要进一步测试……
